locustfile = ./scenarios/grpc/gateway/new_user_make_top_up_operation/scenario.py
spawn-rate = 30
run-time = 3m
headless = true
users = 300
html = ./scenarios/grpc/gateway/new_user_make_top_up_operation/report.html